apiVersion: v1
kind: ConfigMap
metadata:
  name: churn-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/model.joblib
  MODEL_NAME: bank-churn
  MODEL_ALIAS: prod
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000