name: ci
on: 
  push: {branches:[main]}
  pull_request: 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkoout@7
      - uses: astral-sh/setup-uv@7
        with: {enable-chash: true}
      - run: uv sync --frozen
      - run: uv run ruff check .
      - run: uv run pytest 